services:
  image-processor:
    image: ghcr.io/LeiseLeo/social-board-processor:latest

    volumes:
      - ./images:/images

    restart: unless-stopped

  web:
    image: ghcr.io/LeiseLeo/social-board:latest

    ports:
      - '127.0.0.1:8080:80'

    volumes:
      - ./images/generated:/usr/share/nginx/html/images:ro

    depends_on:
      - image-processor

    restart: unless-stopped
