server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Angular SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Generated images and image configuration
    location /images/ {
        try_files $uri =404;
    }
}